name: "Upload artifacts to PlayStore"
description: "Uploads an APK or AAB to a PlayStore internal test"
author: "Gerard Sala"
inputs:
  serviceAccountKeyPath:
    required: true
    description: "File path to the Google Play service account key"
  packageName:
    required: true
    description: "Package name (application id)"
  bundlePath:
    required: true
    description: "File path to the release file to be uploaded (.apk/.aab)"
  proguardMappingFilePath:
    required: false
    description: "File path to a Proguard/R8 mapping file to be uploaded in addition to an APK"
  inAppUpdatePriority:
    description: "In-app update priority. Integer from 0 to 5 (inclusive). Defaults to 0 (lowest priority)."
    default: "0"
    required: false
outputs:
  internal-sharing-url:
    description: "URL for internal sharing of the uploaded app"
runs:
  using: "node24"
  main: "dist/index.js"
