name: Test get-xcode-build-destination
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - get-xcode-build-destination/**
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Run tests
        working-directory: get-xcode-build-destination
        run: node --test
